# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SurabayaDev
email: support@surabayadev.com
description: > # this means to ignore newlines until "baseurl:"
  Surabaya Dev adalah komunitas kreatif di surabaya
baseurl: "" # the subpath of your site, e.g. /blog
tagline: "Rundingan - Nambah Elmu - Akeh Konco"
url: "http://surabayadev.com" # the base hostname & protocol for your site
twitter_username: surabayadev
github_username:  surabayadev

# Build settings
markdown: kramdown
